### PR TITLE
A simple cricket theme

### PR DESCRIPTION
**Pull request by Paulsonp**

### CODE REVIEW

**Comment by Paulsonp** [comment]
CLA signed

**Comment by Paulsonp** [comment]
@cla-bot check  Please to recheck

**Comment by rdlauer** [comment]
Thanks for your submission! However, the iOS version crashes on startup. Can you check it on iOS and fix the issue?

**Comment by Paulsonp** [comment]
> Thanks for your submission! However, the iOS version crashes on startup. Can you check it on iOS and fix the issue?

Fixed the issue please check 
Thank you,

**Comment by rdlauer** [comment]
Hmmm, I see the loading screen now, but when I tap "continue" the app crashes again.

**Comment by Paulsonps** [comment]
Fixed now please try it new playground version 5
https://play.nativescript.org/?template=play-ng&id=R9GFpP&v=5

**Comment by rdlauer** [comment]
Thanks! I'm going to close this PR and add the app manually to avoid some conflicts.

**Pull request closed without merging**
