### PR TITLE
added a custom material design FAB sample

### PR DESCRIPTION
**Pull request by carloscabral**
Hi, guys. 

New sample added! A custom material design FAB with fancy animations.

Kindest regards,
Carlos.

### CODE REVIEW

**Comment by rdlauer** [comment]
Thanks @carloscabral - I can't seem to run this on my Android device (7.0 at least). Can you check on your end?

**Comment by carloscabral** [comment]
Hi, @rdlauer 
Hmmm, that's weird. Is there anything showing in the console? It works fine on my iPhone.
I'll try to test later on an Android phone.

**Comment by carloscabral** [comment]
Hi, @rdlauer. I was able to reproduce this error on a physical Android phone. The sample works fine on an iPhone 6 and iPhone X though.

The issue seems to be related with this thread: https://github.com/bradmartin/nativescript-cardview/issues/86 

@bradmartin suggest updating the Android build tools. What can we do in this scenario when it comes to Playground?

**Comment by tjvantoll** [comment]
The card view plugin requires an Android library (see https://github.com/bradmartin/nativescript-cardview/blob/cf468086d6d964f35fdb55fef6134ab2569c8949/src/platforms/android/include.gradle), so that plugin will not work in Playground for Android.

Is the CardView plugin essential for showing off the FAB button? If no I’d try to remove it.

If yes, you could maybe sniff for Android and show some warning text instead of crashing Something like—This example makes use of the nativescript-cardview plugin, which does not run in NativeScript Playground. No worries though; you can use Playground’s Download button to download this app, and run this example locally using the NativeScript CLI.

**Comment by shiv19** [comment]
Link to the gif in this PR is a 404

**Comment by b02505048** [comment]
Hi @carloscabral, this is a very useful example! Great job! 👍

By the way, is there any way to make <FabItem> tapped? Cheers

**Pull request closed without merging**
