### PR TITLE
Example of fully functional bottom navigation bar for Android.

### PR DESCRIPTION
**Pull request by sowrensen**
This is an example of implementing a working bottom navigation for Android using NS components. I haven't tried with iOS, but may be it should work.

### CODE REVIEW

**Comment by rdlauer** [comment]
Can you make it compatible with iOS? As of right now it crashes due to Android-specific code being executed.

**Comment by sowrensen** [comment]
Oops.. I would love to. Unfortunately I don't have a mac. Sorry. ☹️

**Comment by rdlauer** [comment]
You don't need a Mac with the Playground :) just an iOS device. If you don't have one I'd be happy to help out. I think the main problem is line 14 of app.ts. If you can do two things:

1) Wrap that in a conditional to prevent it from running on iOS.
2) Show a dialog on iOS only notifying the user that it only works on Android.

I can test the app out for you on iOS.

**Comment by sowrensen** [comment]
@rdlauer Thanks a lot. I have added those lines, hope it will not crash anymore. :smiley:

**Comment by rdlauer** [comment]
It's close! The app no longer crashes, but the alert dialog does not show up. I don't think you can have any UI functionality in your app.ts. If you move that alert to the first view it should work though.

**Comment by sowrensen** [comment]
Absolutely. My bad, I didn't notice. Fixed now.

**Comment by rdlauer** [comment]
Thanks!

**Pull request merged**
