### PR TITLE
adding instagram clone sample

### PR DESCRIPTION
**Pull request by kumarandena**
Instagram clone gif - [https://github.com/kumarandena/nativescript-instagram-clone/blob/master/assets/instaclone.gif](url)

### CODE REVIEW

**Comment by rdlauer** [comment]
Looks really nice! Two issues that I'm seeing though:

1) Menu taps are some times not registered. Not sure if it's a "bounding box" thing (too small) or if there is actually a performance issue?

2) On iOS some of the fonts are not coming through:

image-1

**Comment by rdlauer** [comment]
New link: https://play.nativescript.org/?template=play-ng&id=QMY4lW

**Comment by rdlauer** [comment]
@kumarandena The tabs look and feel good, but the font is still not updating for me on iOS:

image-1

**Comment by kumarandena** [comment]
@rdlauer I have fixed the fonts on iOS in all the Instagram clone screens. The issue is because of `HtmlView` restricts a lot of the styling on iOS. I just replaced it with `FormattedString`. Now both iOS fonts and menu taps works fine. 

Here is the latest playground version - https://play.nativescript.org/?template=play-ng&id=QMY4lW&v=2

**Pull request merged**
